---

- include: init_directory.yml
  vars: 
        directory: 'pycharm'

- unarchive:
       src: https://download.jetbrains.com/python/pycharm-community-2017.1.4.tar.gz
       dest: "{{ final_destination }}/pycharm"
       remote_src: True 
